// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXrWf4LSDnpwd-PA0nZmO0stR9HTTY6Ro',
    appId: '1:514552196725:web:37e8dec4b940a5ed2a523c',
    messagingSenderId: '514552196725',
    projectId: 'car-rental-app-286ca',
    authDomain: 'car-rental-app-286ca.firebaseapp.com',
    storageBucket: 'car-rental-app-286ca.firebasestorage.app',
    measurementId: 'G-CHYSTSRNY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAHIF5T_JHquvZ191DKH21KOd2zCHCRBc',
    appId: '1:514552196725:android:d0358146aa51b5682a523c',
    messagingSenderId: '514552196725',
    projectId: 'car-rental-app-286ca',
    storageBucket: 'car-rental-app-286ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBUGysMczzedO7Zflf5YZqAYx6Vy67lp4',
    appId: '1:514552196725:ios:d209388b5778a3092a523c',
    messagingSenderId: '514552196725',
    projectId: 'car-rental-app-286ca',
    storageBucket: 'car-rental-app-286ca.firebasestorage.app',
    iosBundleId: 'com.example.carRentalAppFirebase',
  );
}
